site_name: SwiftWing 产品介绍 文档

site_description: SwiftWing 产品介绍 文档
site_author: SwiftWing 团队
site_url: https://swiftwing001.github.io/SwiftWing-Parts-Introduction/

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - 产品介绍:
    - P1无人机分电板:
      - 概述: 分电板/0_P1无人机分电板.md
      - 使用说明: 分电板/使用说明.md
    - 迅翼MS4525DO空速计:
      - 概述: 空速/1_迅翼MS4525DO空速计.md
      - 使用说明: 空速/使用说明.md
    - 迅翼Mlrs:
      - 概述: mlrs/产品介绍/mLRS快速上手指南.md
      - 硬件功能: mlrs/产品介绍/硬件功能.md
      - 查看及更改参数: mlrs/产品介绍/mLRS查看及更改参数.md
      - 连接飞控使用: mlrs/产品介绍/mLRS连接飞控使用.md
    - 迅翼Elrs:
      - 快速上手: elrs/elrs接收机快速上手.md
      - 硬件接口介绍: elrs/硬件接口介绍.md
      - 固件刷写: elrs/固件刷写.md
      - 飞控配置: elrs/飞控配置.md
      


# # 本地编译
# mkdocs build
# # 本地预览确认
# mkdocs serve
# # 提交源码到 main 分支
# git add .
# git commit -m "更新内容"
# git push origin master
# # 部署到 GitHub Pages
# mkdocs gh-deploy
# python -m mkdocs build
# python -m mkdocs serve -a 0.0.0.0:8080
# python -m mkdocs serve -a 192.168.31.42:8080
# 192.168.31.42:8080
# 127.0.0.1:8080